//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace waifu2x_ncnn_vulkan_GUI_Edition_C_Sharp {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("waifu2x_ncnn_vulkan_GUI_Edition_C_Sharp.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Failed to extract the audio file.
        ///If you have enabled advanced settings, please check your settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AudioNot {
            get {
                return ResourceManager.GetString("AudioNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reupscaling Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonReUpscaleVideo {
            get {
                return ResourceManager.GetString("ButtonReUpscaleVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upscaling Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonUpscaleVideo {
            get {
                return ResourceManager.GetString("ButtonUpscaleVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current version: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CurrentString {
            get {
                return ResourceManager.GetString("CurrentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting files, Please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DELProgress {
            get {
                return ResourceManager.GetString("DELProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   files deleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DELScalled {
            get {
                return ResourceManager.GetString("DELScalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Upscalled Images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FBDImageTitle {
            get {
                return ResourceManager.GetString("FBDImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some fields are not entered correctly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FieldError {
            get {
                return ResourceManager.GetString("FieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image (*.jpg;*.png;*.webp)|*.jpg;*.png;*.webp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterImage {
            get {
                return ResourceManager.GetString("FilterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video (*.avi;*.mp4;*.mov;*.wmv;*.mkv;*.webm)|*.avi;*.mp4;*.mov;*.wmv;*.mkv;*.webm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FilterVideo {
            get {
                return ResourceManager.GetString("FilterVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IMGS {
            get {
                return ResourceManager.GetString("IMGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   image upscaled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IMGScalled {
            get {
                return ResourceManager.GetString("IMGScalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   images upscaled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IMGSScalled {
            get {
                return ResourceManager.GetString("IMGSScalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image upscaling has been completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IMGUP {
            get {
                return ResourceManager.GetString("IMGUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to upscale the image. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IMGUPError {
            get {
                return ResourceManager.GetString("IMGUPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialized... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Initalize {
            get {
                return ResourceManager.GetString("Initalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest version: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LatestString {
            get {
                return ResourceManager.GetString("LatestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split the video frame...
        ///Please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MERGEProgress {
            get {
                return ResourceManager.GetString("MERGEProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   frames に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MERGEScalled {
            get {
                return ResourceManager.GetString("MERGEScalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file already exists in the specified folder.
        ///If the process is executed as is, all files in the specified folder will be lost.
        ///Do you wish to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGAlready {
            get {
                return ResourceManager.GetString("MSGAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGConfirm {
            get {
                return ResourceManager.GetString("MSGConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGError {
            get {
                return ResourceManager.GetString("MSGError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGInfo {
            get {
                return ResourceManager.GetString("MSGInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSGWarning {
            get {
                return ResourceManager.GetString("MSGWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Readed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotReadedString {
            get {
                return ResourceManager.GetString("NotReadedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Upscaling Image(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OFDImageTitle {
            get {
                return ResourceManager.GetString("OFDImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Upscaling Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OFDVideoTitle {
            get {
                return ResourceManager.GetString("OFDVideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing is currently in progress.
        ///If you stop the process, all of the currently executed process contents will be lost.
        ///Do you want to abort the process? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressAbortConfirm {
            get {
                return ResourceManager.GetString("ProgressAbortConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The process has been aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProgressAborted {
            get {
                return ResourceManager.GetString("ProgressAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Readed! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadedString {
            get {
                return ResourceManager.GetString("ReadedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operation cannot be continued because the settings are not correct.
        ///Please configure the settings from the &apos;Settings&apos; item. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingError {
            get {
                return ResourceManager.GetString("SettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Upscalled Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SFDImageTitle {
            get {
                return ResourceManager.GetString("SFDImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Upscalled Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SFDVideoTitle {
            get {
                return ResourceManager.GetString("SFDVideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bytes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SizeString {
            get {
                return ResourceManager.GetString("SizeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnExpectedError {
            get {
                return ResourceManager.GetString("UnExpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update is available.
        ///Do you want to open the site? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateConfirm {
            get {
                return ResourceManager.GetString("UpdateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upscaling Image, Please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UPIMGProgress {
            get {
                return ResourceManager.GetString("UPIMGProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upscaling Images, Please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UPIMGSProgress {
            get {
                return ResourceManager.GetString("UPIMGSProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are using the latest version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Uptodate {
            get {
                return ResourceManager.GetString("Uptodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upscaling video frames, Please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UPVProgress {
            get {
                return ResourceManager.GetString("UPVProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reupscaling video frames, Please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UPVRProgress {
            get {
                return ResourceManager.GetString("UPVRProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video resolution has been changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VRCNG {
            get {
                return ResourceManager.GetString("VRCNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed change video resolution. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VRCNGError {
            get {
                return ResourceManager.GetString("VRCNGError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VROFDTitle {
            get {
                return ResourceManager.GetString("VROFDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   frames re-upscaled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VRScalled {
            get {
                return ResourceManager.GetString("VRScalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VRSFDTitle {
            get {
                return ResourceManager.GetString("VRSFDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video upscaling has been completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VRUP {
            get {
                return ResourceManager.GetString("VRUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upscaling of the video failed.
        ///Please check your settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VRUPError {
            get {
                return ResourceManager.GetString("VRUPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   frames upscaled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VScalled {
            get {
                return ResourceManager.GetString("VScalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upscaling is now complete.
        ///If you want to do more upscaling, click &apos;Reupscaling Video&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VUP {
            get {
                return ResourceManager.GetString("VUP", resourceCulture);
            }
        }
    }
}
