//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVGE.Localization {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NVGE.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Animation GIF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AnimGIFCaption {
            get {
                return ResourceManager.GetString("AnimGIFCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to download updates? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppUpdateConfirmCaption {
            get {
                return ResourceManager.GetString("AppUpdateConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to extract the audio file.
        ///If you have enabled advanced settings, please check your settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AudioNot {
            get {
                return ResourceManager.GetString("AudioNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reupscaling GIF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonReUpScaleGIF {
            get {
                return ResourceManager.GetString("ButtonReUpScaleGIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reupscaling Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonReUpscaleVideo {
            get {
                return ResourceManager.GetString("ButtonReUpscaleVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upscaling GIF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonUpScaleGIF {
            get {
                return ResourceManager.GetString("ButtonUpScaleGIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upscaling Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonUpscaleVideo {
            get {
                return ResourceManager.GetString("ButtonUpscaleVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is currently an upscaled frame file.
        ///If you exit the application at this point, all upscaled
        ///file will be lost. Are you sure you want to exit? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmClose {
            get {
                return ResourceManager.GetString("ConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The image is being converted.
        ///Please wait a moment... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConvertProgress {
            get {
                return ResourceManager.GetString("ConvertProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   files converted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConvertScalled {
            get {
                return ResourceManager.GetString("ConvertScalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the model to be used when upscaling.
        ///SE: This is selected by default.
        ///Nose: Only &apos;2x&apos; can be specified for the upscaling factor. The denoising option is not available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cuganModelToolTipCaption {
            get {
                return ResourceManager.GetString("cuganModelToolTipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current version: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CurrentString {
            get {
                return ResourceManager.GetString("CurrentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting files, Please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DELProgress {
            get {
                return ResourceManager.GetString("DELProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   files deleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DELScalled {
            get {
                return ResourceManager.GetString("DELScalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The download is currently in progress.
        ///If you stop the process, the downloaded content will be lost.
        ///Are you sure you want to stop the process? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DLAbortConfirm {
            get {
                return ResourceManager.GetString("DLAbortConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFmpeg does not exist. Do you want to download it?
        ///(Internet connection is required to download) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DLConfirm {
            get {
                return ResourceManager.GetString("DLConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}% ({1} KiB out of {2} KiB) Download completed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DLInfo {
            get {
                return ResourceManager.GetString("DLInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file is downloading.
        ///Please wait a moment... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DLProgress {
            get {
                return ResourceManager.GetString("DLProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DLSuccess {
            get {
                return ResourceManager.GetString("DLSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag and drop an image or video file here, or open the file... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DragDropCaption {
            get {
                return ResourceManager.GetString("DragDropCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some fields are not entered correctly.
        ///&apos;Audio codec&apos; value must be at least two characters long. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorACodecNot {
            get {
                return ResourceManager.GetString("ErrorACodecNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is an incorrectly entered field.
        ///The path is not specified in the &apos;Audio destination&apos; field. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorALocNot {
            get {
                return ResourceManager.GetString("ErrorALocNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The block size value is invalid.
        ///The block size value must be &apos;0&apos; (automatic) or greater than &apos;21&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorBlockIncorrect {
            get {
                return ResourceManager.GetString("ErrorBlockIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The block size value is invalid.
        ///The block size value must be &apos;0&apos; (automatic) or less than &apos;5000&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorBlockIncorrect2 {
            get {
                return ResourceManager.GetString("ErrorBlockIncorrect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some fields are not entered correctly.
        ///&apos;GPU Block Size&apos; value must be at least 1 character. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorBlockNot {
            get {
                return ResourceManager.GetString("ErrorBlockNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is an incorrect field to enter.
        ///The path is not specified in the &apos;FFmpeg.exe path&apos; field. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorFFmpegPath {
            get {
                return ResourceManager.GetString("ErrorFFmpegPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some fields are not entered correctly.
        ///The &apos;FPS of upscaled video&apos; field should be entered in the following format
        ///It should be entered in the following format: **. **.
        ///
        ///Example: 60fps &gt; 60.00, 29.97fps &gt; 29.97 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorFPS {
            get {
                return ResourceManager.GetString("ErrorFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some fields are not entered correctly.
        ///&apos;FPS for upscaled video&apos; field must be at least 4 characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorFPSChar {
            get {
                return ResourceManager.GetString("ErrorFPSChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some fields are not entered correctly.
        ///&apos;FPS of upscaled video&apos; field must be specified using &apos;. (dot) to be specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorFPSDot {
            get {
                return ResourceManager.GetString("ErrorFPSDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some fields are not entered correctly.
        ///The &apos;CRF level&apos; value must be at least one character. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorNVENCNot {
            get {
                return ResourceManager.GetString("ErrorNVENCNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some fields are not entered correctly.
        ///&apos;Video codec&apos; value must be at least two characters long. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorVCodecNot {
            get {
                return ResourceManager.GetString("ErrorVCodecNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is an incorrectly entered field.
        ///The path is not specified in the &apos;Video destination&apos; field. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorVLocNot {
            get {
                return ResourceManager.GetString("ErrorVLocNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Upscalled Images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FBDImageTitle {
            get {
                return ResourceManager.GetString("FBDImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path to FFmpeg has not been specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FFmpegLocationNotFoundCaption {
            get {
                return ResourceManager.GetString("FFmpegLocationNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFmpeg can be updated.
        ///Do you want to update it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FFUpdate {
            get {
                return ResourceManager.GetString("FFUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some fields are not entered correctly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FieldError {
            get {
                return ResourceManager.GetString("FieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No file is loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileNotReadedWarning {
            get {
                return ResourceManager.GetString("FileNotReadedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitmap Image (*.bmp,*.dib)|*.bmp;*.dib;|Encapsulated PostScript File/Format (*.eps)|*.eps;|Google webp (*.webp)|*.webp;|Graphics Interchange Format (*.gif)|*.gif;|Icon (*.ico,*.icns)|*.ico;*.icns;|Joint Photographic Experts Group (*.jfif,*.jpg,*.jpe,*.jpeg,*.pjpeg,*.pjp)|*.jfif;*.jpg;*.jpe;*.jpeg;*.pjpeg;*.pjp;|Portable Network Graphics (*.png)|*.png;|QuickDraw Picture (*.pict)|*.pict;|Scalable Vector Graphics (*.svg,*.svgz)|*.svg;*.svgz;|Tagged Image File Format (*.tif,*.tiff)|*.tif;*.tiff;|All supported f [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterImage {
            get {
                return ResourceManager.GetString("FilterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   H.264 MPEG-4 (*.mp4)|*.mp4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterMPEG4 {
            get {
                return ResourceManager.GetString("FilterMPEG4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Audio Video Interleave (*.avi)|*.avi;|MPEG-4 (*.mp4)|*.mp4;|Animation GIF (*.gif)|*.gif;|QuickTime Video (*.mov)|*.mov;|Google WebM (*.webm)|*.webm;|Matroska Video (*.mkv)|*.mkv;|Windows Media Video (*.wmv)|*.wmv;|All Supported Files|*.avi;*.mp4;*.gif;*.mov;*.webm;*.mkv;*.wmv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilterVideo {
            get {
                return ResourceManager.GetString("FilterVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is an unsupported file format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FmtErrorCaption {
            get {
                return ResourceManager.GetString("FmtErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is not possible to load multiple files except for images. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImgOnlyMultipleCaption {
            get {
                return ResourceManager.GetString("ImgOnlyMultipleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IMGS {
            get {
                return ResourceManager.GetString("IMGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   image upscaled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IMGScalled {
            get {
                return ResourceManager.GetString("IMGScalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   images upscaled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IMGSScalled {
            get {
                return ResourceManager.GetString("IMGSScalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image upscaling has been completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IMGUP {
            get {
                return ResourceManager.GetString("IMGUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to upscale the image. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IMGUPError {
            get {
                return ResourceManager.GetString("IMGUPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialized... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Initalize {
            get {
                return ResourceManager.GetString("Initalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latest version: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LatestString {
            get {
                return ResourceManager.GetString("LatestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Split the video frame...
        ///Please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MERGEProgress {
            get {
                return ResourceManager.GetString("MERGEProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   frames に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MERGEScalled {
            get {
                return ResourceManager.GetString("MERGEScalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This option is not available for this model. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModelNotSupportedOptionCaption {
            get {
                return ResourceManager.GetString("ModelNotSupportedOptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file already exists in the specified folder.
        ///If the process is executed as is, all files in the specified folder will be lost.
        ///Do you wish to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSGAlready {
            get {
                return ResourceManager.GetString("MSGAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSGConfirm {
            get {
                return ResourceManager.GetString("MSGConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSGError {
            get {
                return ResourceManager.GetString("MSGError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSGInfo {
            get {
                return ResourceManager.GetString("MSGInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSGWarning {
            get {
                return ResourceManager.GetString("MSGWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiple image files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MultipleImageCaption {
            get {
                return ResourceManager.GetString("MultipleImageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The computer is not connected to the Internet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotNetworkConnectionCaption {
            get {
                return ResourceManager.GetString("NotNetworkConnectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not ready - please open the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotReadedStatusString {
            get {
                return ResourceManager.GetString("NotReadedStatusString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please open the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotReadedString {
            get {
                return ResourceManager.GetString("NotReadedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Reduction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotReductionIndex {
            get {
                return ResourceManager.GetString("NotReductionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Upscaling Image(s) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OFDImageTitle {
            get {
                return ResourceManager.GetString("OFDImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Upscaling Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OFDVideoTitle {
            get {
                return ResourceManager.GetString("OFDVideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open the file to be reformatted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFormatChangeDialogCaption {
            get {
                return ResourceManager.GetString("OpenFormatChangeDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pixel values are not entered correctly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PixelValueNotSetCaption {
            get {
                return ResourceManager.GetString("PixelValueNotSetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing is currently in progress.
        ///If you stop the process, all of the currently executed process contents will be lost.
        ///Do you want to abort the process? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressAbortConfirm {
            get {
                return ResourceManager.GetString("ProgressAbortConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The process has been aborted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressAborted {
            get {
                return ResourceManager.GetString("ProgressAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReadedString {
            get {
                return ResourceManager.GetString("ReadedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the model to be used when upscaling.
        ///Real-ESRGAN: This is selected by default.
        ///Real-ESRGAN Anime: This model is suitable for upscaling illustrations.
        ///Real-ESRGAN Photo: This model is suitable for upscaling photos. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string realesrganModelToolTipCaption {
            get {
                return ResourceManager.GetString("realesrganModelToolTipCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save the reformatted file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFormatChangeDialogCaption {
            get {
                return ResourceManager.GetString("SaveFormatChangeDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operation cannot be continued because the settings are not correct.
        ///Please configure the settings from the &apos;Settings&apos; item. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingError {
            get {
                return ResourceManager.GetString("SettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Upscalled Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SFDImageTitle {
            get {
                return ResourceManager.GetString("SFDImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Upscalled Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SFDVideoTitle {
            get {
                return ResourceManager.GetString("SFDVideoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bytes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SizeString {
            get {
                return ResourceManager.GetString("SizeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking configuration information... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SplashFormConfigCaption {
            get {
                return ResourceManager.GetString("SplashFormConfigCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check for FFmpeg updates... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SplashFormFFCaption {
            get {
                return ResourceManager.GetString("SplashFormFFCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loaded: &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SplashFormFileCaption {
            get {
                return ResourceManager.GetString("SplashFormFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SplashFormFinalCaption {
            get {
                return ResourceManager.GetString("SplashFormFinalCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Getting system information... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SplashFormSystemCaption {
            get {
                return ResourceManager.GetString("SplashFormSystemCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check for updates... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SplashFormUpdateCaption {
            get {
                return ResourceManager.GetString("SplashFormUpdateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Successfuly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SplashFormUpdatedCaption {
            get {
                return ResourceManager.GetString("SplashFormUpdatedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Updating application... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SplashFormUpdatingCaption {
            get {
                return ResourceManager.GetString("SplashFormUpdatingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected error has occurred.
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnExpectedError {
            get {
                return ResourceManager.GetString("UnExpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFmpeg exists, but the version is unknown.
        ///Do you want to download the official version? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UnknownFFmpegCaption {
            get {
                return ResourceManager.GetString("UnknownFFmpegCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The update has been completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateCompletedCaption {
            get {
                return ResourceManager.GetString("UpdateCompletedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update is available.
        ///Do you want to open the site? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateConfirm {
            get {
                return ResourceManager.GetString("UpdateConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upscaling Image, Please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UPIMGProgress {
            get {
                return ResourceManager.GetString("UPIMGProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upscaling Images, Please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UPIMGSProgress {
            get {
                return ResourceManager.GetString("UPIMGSProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   x に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UplevelCaption {
            get {
                return ResourceManager.GetString("UplevelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are using the latest version. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Uptodate {
            get {
                return ResourceManager.GetString("Uptodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upscaling video frames, Please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UPVProgress {
            get {
                return ResourceManager.GetString("UPVProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reupscaling video frames, Please wait... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UPVRProgress {
            get {
                return ResourceManager.GetString("UPVRProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VideoCaption {
            get {
                return ResourceManager.GetString("VideoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format conversion failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VideoFormatChange_ErrorCaption {
            get {
                return ResourceManager.GetString("VideoFormatChange_ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The source and destination files cannot be in the same format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VideoFormatChange_FmtErrorCaption {
            get {
                return ResourceManager.GetString("VideoFormatChange_FmtErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format conversion has been completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VideoFormatChange_SuccessCaption {
            get {
                return ResourceManager.GetString("VideoFormatChange_SuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video resolution has been changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VRCNG {
            get {
                return ResourceManager.GetString("VRCNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed change video resolution. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VRCNGError {
            get {
                return ResourceManager.GetString("VRCNGError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VROFDTitle {
            get {
                return ResourceManager.GetString("VROFDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   frames re-upscaled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VRScalled {
            get {
                return ResourceManager.GetString("VRScalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VRSFDTitle {
            get {
                return ResourceManager.GetString("VRSFDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video upscaling has been completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VRUP {
            get {
                return ResourceManager.GetString("VRUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upscaling of the video failed.
        ///Please check your settings. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VRUPError {
            get {
                return ResourceManager.GetString("VRUPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   frames upscaled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VScalled {
            get {
                return ResourceManager.GetString("VScalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upscaling is now complete.
        ///If you want to do more upscaling, click &apos;Reupscaling Video&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VUP {
            get {
                return ResourceManager.GetString("VUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the model to be used when upscaling.
        ///CUnet: This is selected by default.
        ///RGB: This model is suitable for upscaling illustrations.
        ///Photo: This model is suitable for upscaling photos. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string waifu2xModelToolTipCaption {
            get {
                return ResourceManager.GetString("waifu2xModelToolTipCaption", resourceCulture);
            }
        }
    }
}
